// list of adjectives
const adjectives = [
  "Able",
  "Absent",
  "Absolute",
  "Abstract",
  "Academic",
  "Acceptable",
  "Accessible",
  "Active",
  "Actual",
  "Admirable",
  "Adorable",
  "Adventurous",
  "Affordable",
  "Aggressive",
  "Agile",
  "Ambitious",
  "Amusing",
  "Ancient",
  "Angry",
  "Anxious",
  "Appropriate",
  "Apt",
  "Artistic",
  "Astonishing",
  "Attentive",
  "Attractive",
  "Authentic",
  "Awesome",
  "Balanced",
  "Beautiful",
  "Beneficial",
  "Bold",
  "Brave",
  "Bright",
  "Brilliant",
  "Calm",
  "Capable",
  "Charming",
  "Cheerful",
  "Classic",
  "Clean",
  "Clever",
  "Colorful",
  "Comfortable",
  "Common",
  "Competent",
  "Confident",
  "Conscious",
  "Considerate",
  "Cool",
  "Cooperative",
  "Courageous",
  "Creative",
  "Crisp",
  "Cunning",
  "Cute",
  "Daring",
  "Dazzling",
  "Decent",
];

// list of nouns
const nouns = [
  "Alligator",
  "Antelope",
  "Armadillo",
  "Baboon",
  "Badger",
  "Bear",
  "Beaver",
  "Bee",
  "Bison",
  "Butterfly",
  "Camel",
  "Caterpillar",
  "Cheetah",
  "Chicken",
  "Chimpanzee",
  "Cobra",
  "Coyote",
  "Crab",
  "Crocodile",
  "Crow",
  "Deer",
  "Dinosaur",
  "Dolphin",
  "Dove",
  "Dragonfly",
  "Duck",
  "Eagle",
  "Elephant",
  "Falcon",
  "Flamingo",
  "Fox",
  "Frog",
  "Giraffe",
  "Goose",
  "Gorilla",
  "Grasshopper",
  "Hamster",
  "Hedgehog",
  "Heron",
  "Hippopotamus",
  "Horse",
  "Hummingbird",
  "Hyena",
  "Iguana",
  "Jaguar",
  "Kangaroo",
  "Koala",
  "Leopard",
  "Lion",
  "Lizard",
  "Llama",
  "Lobster",
  "Lynx",
  "Meerkat",
  "Monkey",
  "Moose",
  "Narwhal",
  "Octopus",
  "Opossum",
  "Ostrich",
  "Otter",
  "Owl",
  "Panda",
  "Panther",
  "Parrot",
  "Peacock",
  "Pelican",
  "Penguin",
  "Pig",
  "Pigeon",
];

function generateHandle(adjectives: string[], nouns: string[]): string {
  const randomAdjective = adjectives[randomNumber(adjectives.length)];
  const randomNoun = nouns[randomNumber(nouns.length)];
  return `${randomAdjective}${randomNoun}`;
}

function randomNumber(max: number): number {
  return Math.floor(Math.random() * max);
}

export const generateRandomHandle = () => generateHandle(adjectives, nouns);
